app:
  port: :7500
  mode: prod
  timeout: 5
  secret: secret
db:
  url: root:15962483@tcp(127.0.0.1:3306)/iot?charset=utf8&parseTime=True&loc=Local
log:
  filename: ./logs/gin.log
  maxSize: 128
  maxBackups: 3
  maxAge: 7
  compress: true
